<h2>Python class init</h2>

Whenever a beginner starts learning the Python programming language, they come across something like __init__ which usually they don’t fully understand.

In [1]:
# Understanding python class init function
# Let’s see a short code snippet and see what we’re trying to understand
class Student(object):

    def __init__(self, name):
        print("Init called.")
        self.name = name

    def method(self):
        return self.name 

my_object = Student('Harsha')
my_object.method()

Init called.

'Harsha'

<b>What does the python init method do?</b>

When a new instance of a python class is created, it is the __init__ method which is called and proves to be a very good place where we can modify the object after it has been created.

This means that when we create a new instance of the class like:

In [2]:
my_object = Student('Harsha')

Init called.

<b>Is __init__ the constructor?</b>

Actually yes. __init__ is an oop construct. __init__ is the constructor for a class. Just like mentioned above, the __init__ method is called as soon as the memory for the object is allocated. Let’s see what we did above in our snippet:

In [3]:
def __init__(self, something):
    self.something = something

In [4]:
#Using self is important because if you don’t and implement your method like:
def __init__(self, something):
    _something = something
#The something parameter would be stored in variables on the stack and would be discarded as soon as the __init__ method goes out of scope.

<b>How __init__ works with Inheritance?</b>

In [9]:
#When we have a class inheriting from a superclass, __init__ method works the same way. 
#Let us try to demonstrate what happens when we try to initialise a child class:
class User(object):
    def __init__(self, something):
        print("User Init called.")
        self.something = something

    def method(self):
        return self.something 

class Student(User):
    def __init__(self, something):
        User.__init__(self, something)
        print("Student Init called.")
        self.something = something

    def method(self):
        return self.something 

my_object = Student('Harsha')
my_object.method()

User Init called.
Student Init called.

'Harsha'

In [ ]:
#n above code, when we initialised the Student object, this will be the output which is created when we ran the above program:
#So, before the child class, the parent’s class init was called. You can control this by modifying the order in which the init is called for a parent or a child class.
#To summarise, python __init__ is what is called as a constructor in other OOPs languages such as C++ and Java. 
#The basic idea behind this is, it a special method which is automatically called when an object of that Class is created.

In [ ]:
<h2>Packages and Modules with PIP</h2>

<h3>Python Modules</h3>

Modules refer to a file containing Python statements and definitions.

A file containing Python code, for e.g.: example.py, is called a module and its module name would be example.

We use modules to break down large programs into small manageable and organized files. Furthermore, modules provide reusability of code.

We can define our most used functions in a module and import it, instead of copying their definitions into different programs.

# Python Module example
def add(a, b):
   """This program adds two
   numbers and return the result"""
   result = a + b
   return result

1.Created a file called example.py in the current folder with above definition
2.Now we can import this moudle into our python notebook

import example
example.add(4,5.5)

1.Python has 100's of standard modules available.U can import it in the same way.

<h3>Ways to import python module</h3>

# import statement example
# to import standard module math

import math
print("The value of pi is", math.pi)

# Import with renaming
import math as m
print("The value of pi is", m.pi)

#Python from...import statement
from math import pi
print("The value of pi is", pi)

#Import all names
from math import *
print("The value of pi is", pi)

<h3>The dir() built-in function</h3>

We can use the dir() function to find out names that are defined inside a module

dir(math)

import math
math.__name__

dir()

import sys
sys.path

import example
example.__file__

import re
re.__file__

<h2>Python Package</h2>

Suppose you have developed a very large application that includes many modules. As the number of modules grows, it becomes difficult to keep track of them all if they are dumped into one location. This is particularly so if they have similar names or functionality. You might wish for a means of grouping and organizing them.

Packages allow for a hierarchical structuring of the module namespace using dot notation. In the same way that modules help avoid collisions between global variable names, packages help avoid collisions between module names.

Creating a package is quite straightforward, since it makes use of the operating system’s inherent hierarchical file structure. Consider the following arrangement:

![pkg1.9af1c7aea48f.png](attachment:pkg1.9af1c7aea48f.png)

#mod1.py
def foo():
    print('[mod1] foo()')

class Foo:
    pass

#mod2.py
def bar():
    print('[mod2] bar()')

class Bar:
    pass

import pkg.mod1, pkg.mod2
from pkg.mod1 import foo

from pkg.sub_pkg1.mod1 import foo

![image.png](attachment:image.png)

import pkg.sub_pkg1.mod1

from pkg.sub_pkg1 import mod2

from pkg.sub_pkg2.mod3 import baz

<h2>Install Packages with PIP</h2>

#Install a package from PyPI:
pip install SomePackage
#Install a package that’s already been downloaded from PyPI or obtained from elsewhere. This is useful if the target machine does not have a network connection:
pip install SomePackage-1.0-py2.py3-none-any.whl
#Show what files were installed:
    pip show --files SomePackage
#List what packages are outdated:
pip list --outdated
#Upgrade a package:
pip install --upgrade SomePackage
#Uninstall a package:
pip uninstall SomePackage

<h2>exceptions in Python</h2>

Python has many built-in exceptions which forces your program to output an error when something in it goes wrong.

When these exceptions occur, it causes the current process to stop and passes it to the calling process until it is handled. If not handled, our program will crash.

For example, if function A calls function B which in turn calls function C and an exception occurs in function C. If it is not handled in C, the exception passes to B and then to A.

If never handled, an error message is spit out and our program come to a sudden, unexpected halt.

<h2>Catching Exceptions in Python</h2>

# import module sys to get the type of exception
import sys

randomList = ['a', 0, 2]

for entry in randomList:
    try:
        print("The entry is", entry)
        r = 1/int(entry)
        break
    except:
        print("Oops!",sys.exc_info()[0],"occured.")
        print("Next entry.")
        print()
print("The reciprocal of",entry,"is",r)

#If no exception occurs, except block is skipped and normal flow continues. But if any exception occurs, 

#it is caught by the except block.

#Here, we print the name of the exception using ex_info() function inside sys module and ask the user to try again.
#We can see that the values 'a' and '1.3' causes ValueError and '0' causes ZeroDivisionError.

<h2>Catching Specific Exceptions in Python</h2>

#This is not a good programming practice as it will catch all exceptions and handle every case in the same way. 
#We can specify which exceptions an except clause will catch.

#A try clause can have any number of except clause to handle them differently but only one will be executed 
#in case an exception occurs.

#We can use a tuple of values to specify multiple exceptions in an except clause. Here is an example pseudo code.

try:
   # do something
   pass
except ValueError:
   # handle ValueError exception
   pass
except (TypeError, ZeroDivisionError):
   # handle multiple exceptions
   # TypeError and ZeroDivisionError
   pass
except:
   # handle all other exceptions
   pass

<h2>Raising Exceptions</h2>

#In Python programming, exceptions are raised when corresponding errors occur at run time, 
#but we can forcefully raise it using the keyword raise.

#We can also optionally pass in value to the exception to clarify why that exception was raised.

raise KeyboardInterrupt
Traceback (most recent call last):
...
KeyboardInterrupt
raise MemoryError("This is an argument")
Traceback (most recent call last):
...
MemoryError: This is an argument
try:
...     a = int(input("Enter a positive integer: "))
...     if a <= 0:
...         raise ValueError("That is not a positive number!")
... except ValueError as ve:
...     print(ve)
...    
Enter a positive integer: -2
That is not a positive number!

<h2>try and finally</h2>

The try statement in Python can have an optional finally clause. This clause is executed no matter what, and is generally used to release external resources.

For example, we may be connected to a remote data center through the network or working with a file or working with a Graphical User Interface (GUI).

In all these circumstances, we must clean up the resource once used, whether it was successful or not. These actions (closing a file, GUI or disconnecting from network) are performed in the finally clause to guarantee execution.

try:
   f = open("test.txt",encoding = 'utf-8')
   # perform file operations
finally:
   f.close()

<h2>Python User Defined Exceptions</h2>

Python has many built-in exceptions which forces your program to output an error when something in it goes wrong.

However, sometimes you may need to create custom exceptions that serves your purpose.

In Python, users can define such exceptions by creating a new class. This exception class has to be derived, either directly or indirectly, from Exception class. Most of the built-in exceptions are also derived form this class.

class CustomError(Exception):
...     pass
...
>>> raise CustomError
Traceback (most recent call last):
...
__main__.CustomError
>>> raise CustomError("An error occurred")
Traceback (most recent call last):
...
__main__.CustomError: An error occurred

Here, we have created a user-defined exception called CustomError which is derived from the Exception class. This new exception can be raised, like other exceptions, using the raise statement with an optional error message.

When we are developing a large Python program, it is a good practice to place all the user-defined exceptions that our program raises in a separate file. Many standard modules do this. They define their exceptions separately as exceptions.py or errors.py (generally but not always).

User-defined exception class can implement everything a normal class can do, but we generally make them simple and concise. Most implementations declare a custom base class and derive others exception classes from this base class. This concept is made clearer in the following example.

<h2>User-Defined Exception in Python</h2>

# define Python user-defined exceptions
class Error(Exception):
   """Base class for other exceptions"""
   pass
class ValueTooSmallError(Error):
   """Raised when the input value is too small"""
   pass
class ValueTooLargeError(Error):
   """Raised when the input value is too large"""
   pass
# our main program
# user guesses a number until he/she gets it right
# you need to guess this number
number = 10
while True:
   try:
       i_num = int(input("Enter a number: "))
       if i_num < number:
           raise ValueTooSmallError
       elif i_num > number:
           raise ValueTooLargeError
       break
   except ValueTooSmallError:
       print("This value is too small, try again!")
       print()
   except ValueTooLargeError:
       print("This value is too large, try again!")
       print()
print("Congratulations! You guessed it correctly.")

In [ ]:
# File Operations 

<h3>What is a file?</h3>

<b>A file is some information or data which stays in the computer storage devices. You already know about different kinds of file , like your music files, video files, text files. Python gives you easy ways to manipulate these files. Generally we divide files in two categories, text file and binary file. Text files are simple text where as the binary files contain binary data which is only readable by computer.</b>

<h3>End of Line Character in a text file</h3>

<b>Each line is terminated with a special character, called the EOL or End of Line character. There are several types, but the most common is the comma {,} or newline character. It ends the current line and tells the interpreter a new one has begun. 

A backslash character can also be used, and it tells the interpreter that the next character – following the slash – should be treated as a new line. This character is useful when you don’t want to start a new line in the text itself but in the code. </b>

<b>Ex: Harsha.txt, config.py, param.xml, data.csv</b>

<h3>Directories and file management in python</h3>

<b>Directory is nothing but a folder/location where it can store files, subfolders.
To acces the folders and files in python, we have a module named os.</b>
<br>

<b>os module has diffrent methods to handle both directories and files in python</b>

<h3>Create , Delete and rename directories in python using os module. Navigating directories in python</h3>

import os
#get current working directory
os.getcwd()

'D:\\\Data_Science\\\Batch1_Lessons'--> The '\\' indicates the escape sequence of the file path. If we want to print only single slash , we can print it using print() function

print(os.getcwd())

#Finding list of files in the directory 
os.listdir("D:\Work")
#it lists all the files in the current working directory

#Finding list of files in a specific directory
os.listdir("D:\\Data_Science")

#Change the current working directory
os.chdir('D:\\Data_Science')
print(os.getcwd())

os.chdir('D:\\Data_Science\\Batch1_Lessons')
print(os.getcwd())

#Create a directory
os.mkdir('test')
#by default if dont specify the fully qualified path, then it will create a folder in the current working directory

#Create a directory under specific folder
os.mkdir('D:\\Data_Science\\DS_Task\\test1')

os.listdir()

#Rename a folder
os.rename('test','test_changed')
os.listdir()

os.listdir("D:\\Data_Science\\Batch1_Lessons\\test_changed")

#Delete a folder, file 
os.rmdir('test_changed')
#You can't delete a not empty directory, u should delete the files inside the directory and delete the folder

os.remove('D:\\Data_Science\\Batch1_Lessons\\test_changed\\abc.txt')

#Delete a folder, file 
#os.chmod('D:\\Data_Science\\Batch1_Lessons\\test_changed', 0777)
os.rmdir('D:\\Data_Science\\Batch1_Lessons\\test_changed')

os.listdir("D:\\Data_Science\\Batch1_Lessons")

 #To remove the directory with all files inside it, we can use shutil module
import shutil
shutil.rmtree('test_changed')

os.listdir()

# File Operations

<h3>What is a file?</h3>

<b>A file is some information or data which stays in the computer storage devices. You already know about different kinds of file , like your music files, video files, text files. Python gives you easy ways to manipulate these files. Generally we divide files in two categories, text file and binary file. Text files are simple text where as the binary files contain binary data which is only readable by computer.</b>

<h3>End of Line Character in a text file</h3>

<b>Each line is terminated with a special character, called the EOL or End of Line character. There are several types, but the most common is the comma {,} or newline character. It ends the current line and tells the interpreter a new one has begun. 

A backslash character can also be used, and it tells the interpreter that the next character – following the slash – should be treated as a new line. This character is useful when you don’t want to start a new line in the text itself but in the code. </b>

<b>Ex: Harsha.txt, config.py, param.xml, data.csv</b>

<h3>Directories and file management in python</h3>

<b>Directory is nothing but a folder/location where it can store files, subfolders.
To acces the folders and files in python, we have a module named os.</b>
<br>

<b>os module has diffrent methods to handle both directories and files in python</b>

<h3>Create , Delete and rename directories in python using os module. Navigating directories in python</h3>

In [3]:
import os
#get current working directory
os.getcwd()

'D:\\Data_Science\\Batch1_Lessons'

'D:\\\Data_Science\\\Batch1_Lessons'--> The '\\' indicates the escape sequence of the file path. If we want to print only single slash , we can print it using print() function

In [4]:
print(os.getcwd())

D:\Data_Science\Batch1_Lessons

In [11]:
#Finding list of files in the directory 
os.listdir("D:\Work")
#it lists all the files in the current working directory

['Ashwinv_status_Harsha.pptx',
 'GE_Ship_Building',
 'Henkel_Video_Analytics',
 'L&T_Ship_Building_IPMS',
 'LNT_Data_Analytics',
 'PDF_Text_Classification',
 'Predective_Maintenance',
 'Video_Analytics']

In [4]:
#Finding list of files in a specific directory
os.listdir("D:\\Data_Science")

['Anaconda',
 'Analytics_Vidya_Hackathon',
 'Analytics_Vidya_Hackathon.zip',
 'Assignments_DonorsChoose_2018',
 'Assignments_DonorsChoose_2018-20190618T112223Z-002.zip',
 'Batch1_Lessons',
 'Blindness_Detection',
 'DS_Materials',
 'DS_Task',
 'DS_Task_Mohan',
 'Machine_Hack_Hackathon',
 'Twitter_Sentiment_Anaysis']

In [5]:
#Change the current working directory
os.chdir('D:\\Data_Science')
print(os.getcwd())

D:\Data_Science

In [14]:
os.chdir('D:\\Data_Science\\Batch1_Lessons')
print(os.getcwd())

D:\Data_Science\Batch1_Lessons

In [381]:
#Create a directory
os.mkdir('test')
#by default if dont specify the fully qualified path, then it will create a folder in the current working directory

In [6]:
#Create a directory under specific folder
os.mkdir('D:\\Data_Science\\DS_Task\\test1')

In [20]:
os.listdir()

['.ipynb_checkpoints',
 'example.py',
 'img1.PNG',
 'img2.PNG',
 'test',
 'Topics_16_hrs.xlsx',
 'Untitled.ipynb',
 'Week2.ipynb',
 'Week_1.ipynb',
 '__pycache__',
 '~$Topics_16_hrs.xlsx']

In [384]:
#Rename a folder
os.rename('test','test_changed')
os.listdir()

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'test' -> 'test_changed'

In [386]:
os.listdir("D:\\Data_Science\\Batch1_Lessons\\test_changed")

['abc.txt']

In [387]:
#Delete a folder, file 
os.rmdir('test_changed')
#You can't delete a not empty directory, u should delete the files inside the directory and delete the folder

OSError: [WinError 145] The directory is not empty: 'test_changed'

In [388]:
os.remove('D:\\Data_Science\\Batch1_Lessons\\test_changed\\abc.txt')

In [389]:
#Delete a folder, file 
#os.chmod('D:\\Data_Science\\Batch1_Lessons\\test_changed', 0777)
os.rmdir('D:\\Data_Science\\Batch1_Lessons\\test_changed')

In [390]:
os.listdir("D:\\Data_Science\\Batch1_Lessons")

['.ipynb_checkpoints',
 '100 Sales Records.csv',
 'example.py',
 'img1.PNG',
 'img2.PNG',
 'ML OCT Agenda.pdf',
 'my_file.txt',
 'test.txt',
 'test1.txt',
 'Topics_16_hrs.xlsx',
 'Untitled.ipynb',
 'Week2.ipynb',
 'Week_1.ipynb',
 '__pycache__',
 '~$Topics_16_hrs.xlsx']

In [52]:
 #To remove the directory with all files inside it, we can use shutil module
import shutil
shutil.rmtree('test_changed')

In [53]:
os.listdir()

['.ipynb_checkpoints',
 'example.py',
 'img1.PNG',
 'img2.PNG',
 'Topics_16_hrs.xlsx',
 'Untitled.ipynb',
 'Week2.ipynb',
 'Week_1.ipynb',
 '__pycache__',
 '~$Topics_16_hrs.xlsx']

In [ ]:
<h2>File operations in python</h2>

#Opening a file 
Syntax : file_object  = open(“filename”, “mode”,encoding = 'utf-8')
#Filename : Name of the file to open and 
#file_object : Open method will returns a object which has inbuilt functions used for file handling.
#Mode   :   It tells the interpreter and developer which way the file will be used.
#Encoding : The default encoding is platform dependent. In windows, it is 'cp1252' but 'utf-8' in Linux.
#Modes of opening a file in python
# 'r'  : Open a file for reading. (default)
# 'w'  : Open a file for writing. Creates a new file if it does not exist or truncates the file if it exists.
# 'x'  : Open a file for exclusive creation. If the file already exists, the operation fails.
# 'a'  : Open for appending at the end of the file without truncating it. Creates a new file if it does not exist.
# 't'  : Open in text mode. (default)
# 'b'  : Open in binary mode.
# 'r+'  :  Special read and write mode, which is used to handle both actions when working with a file 

<h3>Create a text file</h3>

file = open('test.txt','w') 
 
file.write('Hello All\n') 
file.write('Welcome to Verzeo online machine learning internship program\n') 
file.write('This course will help u in learning ML\n') 
file.write('Happy learning!\n') 
file.close() 

#Another way of writing a file 
with open("test1.txt",'w',encoding = 'utf-8') as f:
   f.write("Hello All\n")
   f.write("Good Morning\n\n")
   f.write("Welcome to the session\n")

#This program will create a new file named 'test1.txt' if it does not exist. If it does exist, it is overwritten.
#The advantage using 'with' is, u no need to close the file explicitly.

#Reading/opening a file
#The default mode is read only, ie if you do not provide any mode it will open the file as read only
file = open('test.txt', 'r') 
print(file.read())


#A file operation takes place in the following order.
#Open a file
#Read or write (perform operation)
#Close the file

#Always a opened file should be closed,otherwise it will be stored in the memory and if the same process contnus for multipe files ,
#it will keep adding and finally theprogram could crash

file.close()

#Reading individual lines/ reading with size
file = open("test1.txt",'r',encoding = 'utf-8')

# read the first 5 data.
file.read(3)
#if the text file reading is completed, it will return empty string

#Tell and Seek
file.tell() # Tell will return the current position of the cluster in the file reading.

file.read(5)

file.tell()

#Seek will bring the cursor to the required position back
file.seek(0)

print(file.read(5))
file.tell()

file.seek(5)
print(file.read(5))

#Reading lines in a loop
file1 = open("test1.txt",'r',encoding = 'utf-8')
for x in file1:
    print(x, end='')
file1.close()

with open('test1.txt') as f1:
    for line in f1:
        print(line)

#Readline, Readlines
file = open('test1.txt',encoding = 'utf-8')

#Readline will read line by line till the file ends, if we specify size it will work like read
print(file.readline())
print(file.tell())

#Return all the lines in a list, if all lines are done, it will return empty list
file.readlines()

#Append Data to a File
f=open("test.txt", "a+")
for i in range(2):
     f.write("New line %d\r\n" % (i+1))
f.close()

with open('test.txt') as f1:
    for line in f1:
        print(line)

def main():
    f= open("my_file.txt","w+")
    for i in range(10):
         f.write("This is line %d\r\n" % (i+1))
    f.close()
    #Open the file back and read the contents
    f=open("my_file.txt", "r")
    if f.mode == 'r':
        contents =f.read()
        print (contents)
    #or, readlines reads the individual line into a list
    fl =f.readlines()
    for x in fl:
        print(x)
if __name__== "__main__":
  main()

#List of file functions
# close()          : Close an open file. It has no effect if the file is already closed.
# detach()         : Separate the underlying binary buffer from the TextIOBase and return it.
# fileno()         : Return an integer number (file descriptor) of the file.
# flush()          : Flush the write buffer of the file stream.
# isatty()         : Return True if the file stream is interactive.
# read(n)          : Read atmost n characters form the file. Reads till end of file if it is negative or None.
# readable()       : Returns True if the file stream can be read from.
# readline(n=-1)   : Read and return one line from the file. Reads in at most n bytes if specified.
# readlines(n=-1)  : Read and return a list of lines from the file. Reads in at most n bytes/characters if specified.
# seek(offset,from=SEEK_SET) : Change the file position to offset bytes, in reference to from (start, current, end).
# seekable()       : Returns True if the file stream supports random access.
# tell()           : Returns the current file location.
# truncate(size=None) : Resize the file stream to size bytes. If size is not specified, resize to current location.
# writable()       : Returns True if the file stream can be written to.
# write(s)         : Write string s to the file and return the number of characters written.
# writelines(lines) : Write a list of lines to the file.

<h2>How to read data from csv</h2>

<b>What Is a CSV File?</b>

A CSV file (Comma Separated Values file) is a type of plain text file that uses specific structuring to arrange tabular data. Because it’s a plain text file, it can contain only actual text data—in other words, printable ASCII or Unicode characters.

The structure of a CSV file is given away by its name. Normally, CSV files use a comma to separate each specific data value.

#For example , this is the table data
mydt

#You want to represent above table data in a csv format as below

ID,first_name,company,salary
11,David,Aon,74
12,Jamie,TCS,76
13,Steve,Google,96
14,Stevart,RBS,71
15,John,HCL,78

#In general, the separator character is called a delimiter, and the comma is not the only one used. 
#Other popular delimiters include the tab (\t), colon (:) and semi-colon (;) characters. 
#Properly parsing a CSV file requires us to know which delimiter is being used.

<h3>Using Built-in CSV Library to parse CSV files</h3>

import csv
with open('100 Sales Records.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            print(f'Column names are {", ".join(row)}')
            line_count += 1
        else:
            print(f'''Region:{row[0]}--Country:{row[1]}--Item Type:{row[2]}--Order Date:{row[5]}--Total Profit:{row[12]} \n''')
            line_count += 1
    print(f'Processed {line_count} lines.')

#Loading csv data into a dictionary
import csv
with open('100 Sales Records.csv', mode='r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            print(f'Column names are {", ".join(row)}')
            line_count += 1
        print(f'Region:{row["Region"]}--Country:{row["Country"]}--Item Type:{row["Item Type"]}--Order Date:{row["Order Date"]}--Total Profit:{row["Total Profit"]} \n')
        line_count += 1
    print(f'Processed {line_count} lines.')

The reader object can handle different styles of CSV files by specifying additional parameters, some of which are shown below:

-->delimiter specifies the character used to separate each field. The default is the comma (',').

-->quotechar specifies the character used to surround fields that contain the delimiter character. The default is a double quote (' " ').

-->escapechar specifies the character used to escape the delimiter character, in case quotes aren’t used. The default is no escape character.

import pandas
df = pandas.read_csv('100 Sales Records.csv')
df.head(10)

#Pandas assumes the first line as the header
#Python by default creates a zero based index untill specified any column
#Date columns has to be specially handled in python, otherwise it will consider it as string
import pandas
df = pandas.read_csv('100 Sales Records.csv', index_col='Region')
df.head(10)


df.columns

#Handling date columns in pandas
import pandas
df = pandas.read_csv('100 Sales Records.csv', index_col='Region', parse_dates=['Order Date'])
df.head()

#Giving custom header names
import pandas
df = pandas.read_csv('100 Sales Records.csv', 
            index_col='Region', parse_dates=['Order_Date','Ship_Date'], 
            header=0, 
            names=['Region','Country', 'Item_Type', 'Channel', 'Order_Priority', 'Order_Date',
       'ID', 'Ship_Date', 'Units_Sold', 'Unit_Price', 'Unit_Cost',
       'Total_Revenue', 'Cost', 'Profit'])
df.head()

<h2>File operations in python</h2>

In [ ]:
#Opening a file 
Syntax : file_object  = open(“filename”, “mode”,encoding = 'utf-8')
#Filename : Name of the file to open and 
#file_object : Open method will returns a object which has inbuilt functions used for file handling.
#Mode   :   It tells the interpreter and developer which way the file will be used.
#Encoding : The default encoding is platform dependent. In windows, it is 'cp1252' but 'utf-8' in Linux.
#Modes of opening a file in python
# 'r'  : Open a file for reading. (default)
# 'w'  : Open a file for writing. Creates a new file if it does not exist or truncates the file if it exists.
# 'x'  : Open a file for exclusive creation. If the file already exists, the operation fails.
# 'a'  : Open for appending at the end of the file without truncating it. Creates a new file if it does not exist.
# 't'  : Open in text mode. (default)
# 'b'  : Open in binary mode.
# 'r+'  :  Special read and write mode, which is used to handle both actions when working with a file

<h3>Create a text file</h3>

In [69]:
file = open('test.txt','w') 
 
file.write('Hello All\n') 
file.write('Welcome to Verzeo online machine learning internship program\n') 
file.write('This course will help u in learning ML\n') 
file.write('Happy learning!\n') 
file.close()

In [8]:
#Another way of writing a file 
with open("test1.txt",'w',encoding = 'utf-8') as f:
   f.write("Hello All\n")
   f.write("Good Morning\n\n")
   f.write("Welcome to the session\n")

#This program will create a new file named 'test1.txt' if it does not exist. If it does exist, it is overwritten.
#The advantage using 'with' is, u no need to close the file explicitly.

In [393]:
#Reading/opening a file
#The default mode is read only, ie if you do not provide any mode it will open the file as read only
file = open('test.txt', 'r') 
print(file.read())

Hello All
Welcome to Verzeo online machine learning internship program
This course will help u in learning ML
Happy learning!
New line 1

New line 2

New line 1

New line 2

In [ ]:
#A file operation takes place in the following order.
#Open a file
#Read or write (perform operation)
#Close the file

#Always a opened file should be closed,otherwise it will be stored in the memory and if the same process contnus for multipe files ,
#it will keep adding and finally theprogram could crash

In [417]:
file.close()

In [9]:
#Reading individual lines/ reading with size
file = open("test1.txt",'r',encoding = 'utf-8')

In [10]:
# read the first 5 data.
file.read(3)
#if the text file reading is completed, it will return empty string

'Hel'

In [11]:
#Tell and Seek
file.tell() # Tell will return the current position of the cluster in the file reading.

3

In [12]:
file.read(5)

'lo Al'

In [13]:
file.tell()

8

In [14]:
#Seek will bring the cursor to the required position back
file.seek(0)

0

In [15]:
print(file.read(5))
file.tell()

Hello

5

In [427]:
file.seek(5)
print(file.read(5))

 All

In [429]:
#Reading lines in a loop
file1 = open("test1.txt",'r',encoding = 'utf-8')
for x in file1:
    print(x, end='')
file1.close()

Hello All
Good Morning

Welcome to the session

In [430]:
with open('test1.txt') as f1:
    for line in f1:
        print(line)

Hello All

Good Morning



Welcome to the session

In [16]:
#Readline, Readlines
file = open('test1.txt',encoding = 'utf-8')

In [19]:
#Readline will read line by line till the file ends, if we specify size it will work like read
print(file.readline())
print(file.tell())

27

In [444]:
#Return all the lines in a list, if all lines are done, it will return empty list
file.readlines()

['Hello All\n', 'Good Morning\n', '\n', 'Welcome to the session\n']

In [33]:
#Append Data to a File
f=open("test.txt", "a+")
for i in range(2):
     f.write("New line %d\r\n" % (i+1))
f.close()

In [446]:
with open('test.txt') as f1:
    for line in f1:
        print(line)

Hello All

Welcome to Verzeo online machine learning internship program

This course will help u in learning ML

Happy learning!

New line 1



New line 2



New line 1



New line 2



New line 1



New line 2

In [447]:
def main():
    f= open("my_file.txt","w+")
    for i in range(10):
         f.write("This is line %d\r\n" % (i+1))
    f.close()
    #Open the file back and read the contents
    f=open("my_file.txt", "r")
    if f.mode == 'r':
        contents =f.read()
        print (contents)
    #or, readlines reads the individual line into a list
    fl =f.readlines()
    for x in fl:
        print(x)
if __name__== "__main__":
  main()

This is line 1

This is line 2

This is line 3

This is line 4

This is line 5

This is line 6

This is line 7

This is line 8

This is line 9

This is line 10

In [ ]:
#List of file functions
# close()          : Close an open file. It has no effect if the file is already closed.
# detach()         : Separate the underlying binary buffer from the TextIOBase and return it.
# fileno()         : Return an integer number (file descriptor) of the file.
# flush()          : Flush the write buffer of the file stream.
# isatty()         : Return True if the file stream is interactive.
# read(n)          : Read atmost n characters form the file. Reads till end of file if it is negative or None.
# readable()       : Returns True if the file stream can be read from.
# readline(n=-1)   : Read and return one line from the file. Reads in at most n bytes if specified.
# readlines(n=-1)  : Read and return a list of lines from the file. Reads in at most n bytes/characters if specified.
# seek(offset,from=SEEK_SET) : Change the file position to offset bytes, in reference to from (start, current, end).
# seekable()       : Returns True if the file stream supports random access.
# tell()           : Returns the current file location.
# truncate(size=None) : Resize the file stream to size bytes. If size is not specified, resize to current location.
# writable()       : Returns True if the file stream can be written to.
# write(s)         : Write string s to the file and return the number of characters written.
# writelines(lines) : Write a list of lines to the file.

<h2>How to read data from csv</h2>

<b>What Is a CSV File?</b>

A CSV file (Comma Separated Values file) is a type of plain text file that uses specific structuring to arrange tabular data. Because it’s a plain text file, it can contain only actual text data—in other words, printable ASCII or Unicode characters.

The structure of a CSV file is given away by its name. Normally, CSV files use a comma to separate each specific data value.

In [448]:
#For example , this is the table data
mydt

   ID first_name company  salary
0  11      David     Aon      74
1  12      Jamie     TCS      76
2  13      Steve  Google      96
3  14    Stevart     RBS      71
4  15       John     HCL      78

In [ ]:
#You want to represent above table data in a csv format as below

ID,first_name,company,salary
11,David,Aon,74
12,Jamie,TCS,76
13,Steve,Google,96
14,Stevart,RBS,71
15,John,HCL,78

#In general, the separator character is called a delimiter, and the comma is not the only one used. 
#Other popular delimiters include the tab (\t), colon (:) and semi-colon (;) characters. 
#Properly parsing a CSV file requires us to know which delimiter is being used.

<h3>Using Built-in CSV Library to parse CSV files</h3>

In [205]:
import csv
with open('100 Sales Records.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            print(f'Column names are {", ".join(row)}')
            line_count += 1
        else:
            print(f'''Region:{row[0]}--Country:{row[1]}--Item Type:{row[2]}--Order Date:{row[5]}--Total Profit:{row[12]} \n''')
            line_count += 1
    print(f'Processed {line_count} lines.')

Column names are Region, Country, Item Type, Sales Channel, Order Priority, Order Date, Order ID, Ship Date, Units Sold, Unit Price, Unit Cost, Total Revenue, Total Cost, Total Profit
Region:Australia and Oceania--Country:Tuvalu--Item Type:Baby Food--Order Date:5/28/2010--Total Profit:1582243.50

Region:Central America and the Caribbean--Country:Grenada--Item Type:Cereal--Order Date:8/22/2012--Total Profit:328376.44

Region:Europe--Country:Russia--Item Type:Office Supplies--Order Date:5/2/2014--Total Profit:933903.84

Region:Sub-Saharan Africa--Country:Sao Tome and Principe--Item Type:Fruits--Order Date:6/20/2014--Total Profit:56065.84

Region:Sub-Saharan Africa--Country:Rwanda--Item Type:Office Supplies--Order Date:2/1/2013--Total Profit:2657347.52

Region:Australia and Oceania--Country:Solomon Islands--Item Type:Baby Food--Order Date:2/4/2015--Total Profit:474115.08

Region:Sub-Saharan Africa--Country:Angola--Item Type:Household--Order Date:4/23/2011--Total Profit:2104134.98

Region:Sub-Saharan Africa--Country:Burkina Faso--Item Type:Vegetables--Order Date:7/17/2012--Total Profit:734896.26

Region:Sub-Saharan Africa--Country:Republic of the Congo--Item Type:Personal Care--Order Date:7/14/2015--Total Profit:343986.90

Region:Sub-Saharan Africa--Country:Senegal--Item Type:Cereal--Order Date:4/18/2014--Total Profit:772106.23

Region:Asia--Country:Kyrgyzstan--Item Type:Vegetables--Order Date:6/24/2011--Total Profit:11275.32

Region:Sub-Saharan Africa--Country:Cape Verde--Item Type:Clothes--Order Date:8/2/2014--Total Profit:149381.12

Region:Asia--Country:Bangladesh--Item Type:Clothes--Order Date:1/13/2017--Total Profit:296145.92

Region:Central America and the Caribbean--Country:Honduras--Item Type:Household--Order Date:2/8/2017--Total Profit:4509793.96

Region:Asia--Country:Mongolia--Item Type:Personal Care--Order Date:2/19/2014--Total Profit:277739.67

Region:Europe--Country:Bulgaria--Item Type:Clothes--Order Date:4/23/2012--Total Profit:59960.32

Region:Asia--Country:Sri Lanka--Item Type:Cosmetics--Order Date:11/19/2016--Total Profit:1830670.16

Region:Sub-Saharan Africa--Country:Cameroon--Item Type:Beverages--Order Date:4/1/2015--Total Profit:172619.70

Region:Asia--Country:Turkmenistan--Item Type:Household--Order Date:12/30/2010--Total Profit:1924728.20

Region:Australia and Oceania--Country:East Timor--Item Type:Meat--Order Date:7/31/2012--Total Profit:2154588.52

Region:Europe--Country:Norway--Item Type:Baby Food--Order Date:5/14/2014--Total Profit:1187679.00

Region:Europe--Country:Portugal--Item Type:Baby Food--Order Date:7/31/2015--Total Profit:202941.66

Region:Central America and the Caribbean--Country:Honduras--Item Type:Snacks--Order Date:6/30/2016--Total Profit:216804.00

Region:Australia and Oceania--Country:New Zealand--Item Type:Fruits--Order Date:9/8/2014--Total Profit:15134.04

Region:Europe--Country:Moldova --Item Type:Personal Care--Order Date:5/7/2016--Total Profit:287316.90

Region:Europe--Country:France--Item Type:Cosmetics--Order Date:5/22/2017--Total Profit:477943.95

Region:Australia and Oceania--Country:Kiribati--Item Type:Fruits--Order Date:10/13/2014--Total Profit:37354.16

Region:Sub-Saharan Africa--Country:Mali--Item Type:Fruits--Order Date:5/7/2010--Total Profit:40288.24

Region:Europe--Country:Norway--Item Type:Beverages--Order Date:7/18/2014--Total Profit:162891.96

Region:Sub-Saharan Africa--Country:The Gambia--Item Type:Household--Order Date:5/26/2012--Total Profit:1191019.80

Region:Europe--Country:Switzerland--Item Type:Cosmetics--Order Date:9/17/2012--Total Profit:2280701.13

Region:Sub-Saharan Africa--Country:South Sudan--Item Type:Personal Care--Order Date:12/29/2013--Total Profit:120423.75

Region:Australia and Oceania--Country:Australia--Item Type:Office Supplies--Order Date:10/27/2015--Total Profit:1534983.04

Region:Asia--Country:Myanmar--Item Type:Household--Order Date:1/16/2015--Total Profit:4145955.00

Region:Sub-Saharan Africa--Country:Djibouti--Item Type:Snacks--Order Date:2/25/2017--Total Profit:713942.88

Region:Central America and the Caribbean--Country:Costa Rica--Item Type:Personal Care--Order Date:5/8/2017--Total Profit:363198.03

Region:Middle East and North Africa--Country:Syria--Item Type:Fruits--Order Date:11/22/2011--Total Profit:26185.28

Region:Sub-Saharan Africa--Country:The Gambia--Item Type:Meat--Order Date:1/14/2017--Total Profit:1738477.23

Region:Asia--Country:Brunei--Item Type:Office Supplies--Order Date:4/1/2012--Total Profit:3521431.68

Region:Europe--Country:Bulgaria--Item Type:Office Supplies--Order Date:2/16/2012--Total Profit:2093015.52

Region:Sub-Saharan Africa--Country:Niger--Item Type:Personal Care--Order Date:3/11/2017--Total Profit:170860.05

Region:Middle East and North Africa--Country:Azerbaijan--Item Type:Cosmetics--Order Date:2/6/2010--Total Profit:1904929.22

Region:Sub-Saharan Africa--Country:The Gambia--Item Type:Cereal--Order Date:6/7/2012--Total Profit:247921.87

Region:Europe--Country:Slovakia--Item Type:Vegetables--Order Date:10/6/2012--Total Profit:15549.03

Region:Asia--Country:Myanmar--Item Type:Clothes--Order Date:11/14/2015--Total Profit:212531.20

Region:Sub-Saharan Africa--Country:Comoros--Item Type:Cereal--Order Date:3/29/2016--Total Profit:112659.82

Region:Europe--Country:Iceland--Item Type:Cosmetics--Order Date:12/31/2016--Total Profit:2334947.11

Region:Europe--Country:Switzerland--Item Type:Personal Care--Order Date:12/23/2010--Total Profit:15470.91

Region:Europe--Country:Macedonia--Item Type:Clothes--Order Date:10/14/2014--Total Profit:281057.28

Region:Sub-Saharan Africa--Country:Mauritania--Item Type:Office Supplies--Order Date:1/11/2012--Total Profit:664599.36

Region:Europe--Country:Albania--Item Type:Clothes--Order Date:2/2/2010--Total Profit:81320.96

Region:Sub-Saharan Africa--Country:Lesotho--Item Type:Fruits--Order Date:8/18/2013--Total Profit:66473.52

Region:Middle East and North Africa--Country:Saudi Arabia--Item Type:Cereal--Order Date:3/25/2013--Total Profit:475817.93

Region:Sub-Saharan Africa--Country:Sierra Leone--Item Type:Office Supplies--Order Date:11/26/2011--Total Profit:1814786.72

Region:Sub-Saharan Africa--Country:Sao Tome and Principe--Item Type:Fruits--Order Date:9/17/2013--Total Profit:52848.04

Region:Sub-Saharan Africa--Country:Cote d'Ivoire--Item Type:Clothes--Order Date:6/8/2012--Total Profit:124794.88

Region:Australia and Oceania--Country:Fiji--Item Type:Clothes--Order Date:6/30/2010--Total Profit:354995.20

Region:Europe--Country:Austria--Item Type:Cosmetics--Order Date:2/23/2015--Total Profit:749700.51

Region:Europe--Country:United Kingdom--Item Type:Household--Order Date:1/5/2012--Total Profit:141716.28

Region:Sub-Saharan Africa--Country:Djibouti--Item Type:Cosmetics--Order Date:4/7/2014--Total Profit:1899925.95

Region:Australia and Oceania--Country:Australia--Item Type:Cereal--Order Date:6/9/2013--Total Profit:79869.02

Region:Europe--Country:San Marino--Item Type:Baby Food--Order Date:6/26/2013--Total Profit:757245.00

Region:Sub-Saharan Africa--Country:Cameroon--Item Type:Office Supplies--Order Date:11/7/2011--Total Profit:2896729.28

Region:Middle East and North Africa--Country:Libya--Item Type:Clothes--Order Date:10/30/2010--Total Profit:219197.44

Region:Central America and the Caribbean--Country:Haiti--Item Type:Cosmetics--Order Date:10/13/2013--Total Profit:448977.65

Region:Sub-Saharan Africa--Country:Rwanda--Item Type:Cosmetics--Order Date:10/11/2013--Total Profit:1178928.41

Region:Sub-Saharan Africa--Country:Gabon--Item Type:Personal Care--Order Date:7/8/2012--Total Profit:490535.52

Region:Central America and the Caribbean--Country:Belize--Item Type:Clothes--Order Date:7/25/2016--Total Profit:197048.32

Region:Europe--Country:Lithuania--Item Type:Office Supplies--Order Date:10/24/2010--Total Profit:4350343.52

Region:Sub-Saharan Africa--Country:Madagascar--Item Type:Clothes--Order Date:4/25/2015--Total Profit:263137.28

Region:Asia--Country:Turkmenistan--Item Type:Office Supplies--Order Date:4/23/2013--Total Profit:2630049.60

Region:Middle East and North Africa--Country:Libya--Item Type:Fruits--Order Date:8/14/2015--Total Profit:4657.16

Region:Sub-Saharan Africa--Country:Democratic Republic of the Congo--Item Type:Beverages--Order Date:5/26/2011--Total Profit:182506.39

Region:Sub-Saharan Africa--Country:Djibouti--Item Type:Cereal--Order Date:5/20/2017--Total Profit:1013704.16

Region:Middle East and North Africa--Country:Pakistan--Item Type:Cosmetics--Order Date:7/5/2013--Total Profit:2604860.36

Region:North America--Country:Mexico--Item Type:Household--Order Date:11/6/2014--Total Profit:3494663.16

Region:Australia and Oceania--Country:Federated States of Micronesia--Item Type:Beverages--Order Date:10/28/2014--Total Profit:298158.41

Region:Asia--Country:Laos--Item Type:Vegetables--Order Date:9/15/2011--Total Profit:339350.76

Region:Europe--Country:Monaco--Item Type:Baby Food--Order Date:5/29/2012--Total Profit:1373243.88

Region:Australia and Oceania--Country:Samoa --Item Type:Cosmetics--Order Date:7/20/2013--Total Profit:2542187.82

Region:Europe--Country:Spain--Item Type:Household--Order Date:10/21/2012--Total Profit:2267963.02

Region:Middle East and North Africa--Country:Lebanon--Item Type:Clothes--Order Date:9/18/2012--Total Profit:282562.56

Region:Middle East and North Africa--Country:Iran--Item Type:Cosmetics--Order Date:11/15/2016--Total Profit:1708748.37

Region:Sub-Saharan Africa--Country:Zambia--Item Type:Snacks--Order Date:1/4/2011--Total Profit:398042.40

Region:Sub-Saharan Africa--Country:Kenya--Item Type:Vegetables--Order Date:3/18/2012--Total Profit:587135.01

Region:North America--Country:Mexico--Item Type:Personal Care--Order Date:2/17/2012--Total Profit:363934.74

Region:Sub-Saharan Africa--Country:Sao Tome and Principe--Item Type:Beverages--Order Date:1/16/2011--Total Profit:280673.91

Region:Sub-Saharan Africa--Country:The Gambia--Item Type:Baby Food--Order Date:2/3/2014--Total Profit:886215.78

Region:Middle East and North Africa--Country:Kuwait--Item Type:Fruits--Order Date:4/30/2012--Total Profit:3612.24

Region:Europe--Country:Slovenia--Item Type:Beverages--Order Date:10/23/2016--Total Profit:148141.40

Region:Sub-Saharan Africa--Country:Sierra Leone--Item Type:Office Supplies--Order Date:12/6/2016--Total Profit:497662.08

Region:Australia and Oceania--Country:Australia--Item Type:Beverages--Order Date:7/7/2014--Total Profit:298476.31

Region:Middle East and North Africa--Country:Azerbaijan--Item Type:Office Supplies--Order Date:6/13/2012--Total Profit:1060944.16

Region:Europe--Country:Romania--Item Type:Cosmetics--Order Date:11/26/2010--Total Profit:2082940.30

Region:Central America and the Caribbean--Country:Nicaragua--Item Type:Beverages--Order Date:2/8/2011--Total Profit:259279.24

Region:Sub-Saharan Africa--Country:Mali--Item Type:Clothes--Order Date:7/26/2011--Total Profit:31825.92

Region:Asia--Country:Malaysia--Item Type:Fruits--Order Date:11/11/2011--Total Profit:43367.64

Region:Sub-Saharan Africa--Country:Sierra Leone--Item Type:Vegetables--Order Date:6/1/2016--Total Profit:135031.05

Region:North America--Country:Mexico--Item Type:Personal Care--Order Date:7/30/2015--Total Profit:326815.89

Region:Sub-Saharan Africa--Country:Mozambique--Item Type:Household--Order Date:2/10/2012--Total Profit:2697132.18

Processed 101 lines.

In [210]:
#Loading csv data into a dictionary
import csv
with open('100 Sales Records.csv', mode='r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            print(f'Column names are {", ".join(row)}')
            line_count += 1
        print(f'Region:{row["Region"]}--Country:{row["Country"]}--Item Type:{row["Item Type"]}--Order Date:{row["Order Date"]}--Total Profit:{row["Total Profit"]} \n')
        line_count += 1
    print(f'Processed {line_count} lines.')

Column names are Region, Country, Item Type, Sales Channel, Order Priority, Order Date, Order ID, Ship Date, Units Sold, Unit Price, Unit Cost, Total Revenue, Total Cost, Total Profit
Region:Australia and Oceania--Country:Tuvalu--Item Type:Baby Food--Order Date:5/28/2010--Total Profit:951410.50

Region:Central America and the Caribbean--Country:Grenada--Item Type:Cereal--Order Date:8/22/2012--Total Profit:248406.36

Region:Europe--Country:Russia--Item Type:Office Supplies--Order Date:5/2/2014--Total Profit:224598.75

Region:Sub-Saharan Africa--Country:Sao Tome and Principe--Item Type:Fruits--Order Date:6/20/2014--Total Profit:19525.82

Region:Sub-Saharan Africa--Country:Rwanda--Item Type:Office Supplies--Order Date:2/1/2013--Total Profit:639077.50

Region:Australia and Oceania--Country:Solomon Islands--Item Type:Baby Food--Order Date:2/4/2015--Total Profit:285087.64

Region:Sub-Saharan Africa--Country:Angola--Item Type:Household--Order Date:4/23/2011--Total Profit:693911.51

Region:Sub-Saharan Africa--Country:Burkina Faso--Item Type:Vegetables--Order Date:7/17/2012--Total Profit:510216.66

Region:Sub-Saharan Africa--Country:Republic of the Congo--Item Type:Personal Care--Order Date:7/14/2015--Total Profit:152114.20

Region:Sub-Saharan Africa--Country:Senegal--Item Type:Cereal--Order Date:4/18/2014--Total Profit:584073.87

Region:Asia--Country:Kyrgyzstan--Item Type:Vegetables--Order Date:6/24/2011--Total Profit:7828.12

Region:Sub-Saharan Africa--Country:Cape Verde--Item Type:Clothes--Order Date:8/2/2014--Total Profit:306097.92

Region:Asia--Country:Bangladesh--Item Type:Clothes--Order Date:1/13/2017--Total Profit:606834.72

Region:Central America and the Caribbean--Country:Honduras--Item Type:Household--Order Date:2/8/2017--Total Profit:1487261.02

Region:Asia--Country:Mongolia--Item Type:Personal Care--Order Date:2/19/2014--Total Profit:122819.06

Region:Europe--Country:Bulgaria--Item Type:Clothes--Order Date:4/23/2012--Total Profit:122865.12

Region:Asia--Country:Sri Lanka--Item Type:Cosmetics--Order Date:11/19/2016--Total Profit:1208744.24

Region:Sub-Saharan Africa--Country:Cameroon--Item Type:Beverages--Order Date:4/1/2015--Total Profit:85033.80

Region:Asia--Country:Turkmenistan--Item Type:Household--Order Date:12/30/2010--Total Profit:634745.90

Region:Australia and Oceania--Country:East Timor--Item Type:Meat--Order Date:7/31/2012--Total Profit:337937.60

Region:Europe--Country:Norway--Item Type:Baby Food--Order Date:5/14/2014--Total Profit:714157.00

Region:Europe--Country:Portugal--Item Type:Baby Food--Order Date:7/31/2015--Total Profit:122029.78

Region:Central America and the Caribbean--Country:Honduras--Item Type:Snacks--Order Date:6/30/2016--Total Profit:122686.50

Region:Australia and Oceania--Country:New Zealand--Item Type:Fruits--Order Date:9/8/2014--Total Profit:5270.67

Region:Europe--Country:Moldova --Item Type:Personal Care--Order Date:5/7/2016--Total Profit:127054.20

Region:Europe--Country:France--Item Type:Cosmetics--Order Date:5/22/2017--Total Profit:315574.05

Region:Australia and Oceania--Country:Kiribati--Item Type:Fruits--Order Date:10/13/2014--Total Profit:13009.18

Region:Sub-Saharan Africa--Country:Mali--Item Type:Fruits--Order Date:5/7/2010--Total Profit:14031.02

Region:Europe--Country:Norway--Item Type:Beverages--Order Date:7/18/2014--Total Profit:80241.84

Region:Sub-Saharan Africa--Country:The Gambia--Item Type:Household--Order Date:5/26/2012--Total Profit:392780.10

Region:Europe--Country:Switzerland--Item Type:Cosmetics--Order Date:9/17/2012--Total Profit:1505888.07

Region:Sub-Saharan Africa--Country:South Sudan--Item Type:Personal Care--Order Date:12/29/2013--Total Profit:53252.50

Region:Australia and Oceania--Country:Australia--Item Type:Office Supplies--Order Date:10/27/2015--Total Profit:369155.00

Region:Asia--Country:Myanmar--Item Type:Household--Order Date:1/16/2015--Total Profit:1367272.50

Region:Sub-Saharan Africa--Country:Djibouti--Item Type:Snacks--Order Date:2/25/2017--Total Profit:404010.78

Region:Central America and the Caribbean--Country:Costa Rica--Item Type:Personal Care--Order Date:5/8/2017--Total Profit:160609.54

Region:Middle East and North Africa--Country:Syria--Item Type:Fruits--Order Date:11/22/2011--Total Profit:9119.44

Region:Sub-Saharan Africa--Country:The Gambia--Item Type:Meat--Order Date:1/14/2017--Total Profit:272672.40

Region:Asia--Country:Brunei--Item Type:Office Supplies--Order Date:4/1/2012--Total Profit:846885.00

Region:Europe--Country:Bulgaria--Item Type:Office Supplies--Order Date:2/16/2012--Total Profit:503358.75

Region:Sub-Saharan Africa--Country:Niger--Item Type:Personal Care--Order Date:3/11/2017--Total Profit:75555.90

Region:Middle East and North Africa--Country:Azerbaijan--Item Type:Cosmetics--Order Date:2/6/2010--Total Profit:1257775.58

Region:Sub-Saharan Africa--Country:The Gambia--Item Type:Cereal--Order Date:6/7/2012--Total Profit:187545.03

Region:Europe--Country:Slovakia--Item Type:Vegetables--Order Date:10/6/2012--Total Profit:10795.23

Region:Asia--Country:Myanmar--Item Type:Clothes--Order Date:11/14/2015--Total Profit:435499.20

Region:Sub-Saharan Africa--Country:Comoros--Item Type:Cereal--Order Date:3/29/2016--Total Profit:85223.58

Region:Europe--Country:Iceland--Item Type:Cosmetics--Order Date:12/31/2016--Total Profit:1541705.29

Region:Europe--Country:Switzerland--Item Type:Personal Care--Order Date:12/23/2010--Total Profit:6841.38

Region:Europe--Country:Macedonia--Item Type:Clothes--Order Date:10/14/2014--Total Profit:575916.48

Region:Sub-Saharan Africa--Country:Mauritania--Item Type:Office Supplies--Order Date:1/11/2012--Total Profit:159832.50

Region:Europe--Country:Albania--Item Type:Clothes--Order Date:2/2/2010--Total Profit:166635.36

Region:Sub-Saharan Africa--Country:Lesotho--Item Type:Fruits--Order Date:8/18/2013--Total Profit:23150.46

Region:Middle East and North Africa--Country:Saudi Arabia--Item Type:Cereal--Order Date:3/25/2013--Total Profit:359941.17

Region:Sub-Saharan Africa--Country:Sierra Leone--Item Type:Office Supplies--Order Date:11/26/2011--Total Profit:436446.25

Region:Sub-Saharan Africa--Country:Sao Tome and Principe--Item Type:Fruits--Order Date:9/17/2013--Total Profit:18405.17

Region:Sub-Saharan Africa--Country:Cote d'Ivoire--Item Type:Clothes--Order Date:6/8/2012--Total Profit:255718.08

Region:Australia and Oceania--Country:Fiji--Item Type:Clothes--Order Date:6/30/2010--Total Profit:727423.20

Region:Europe--Country:Austria--Item Type:Cosmetics--Order Date:2/23/2015--Total Profit:495007.89

Region:Europe--Country:United Kingdom--Item Type:Household--Order Date:1/5/2012--Total Profit:46735.86

Region:Sub-Saharan Africa--Country:Djibouti--Item Type:Cosmetics--Order Date:4/7/2014--Total Profit:1254472.05

Region:Australia and Oceania--Country:Australia--Item Type:Cereal--Order Date:6/9/2013--Total Profit:60418.38

Region:Europe--Country:San Marino--Item Type:Baby Food--Order Date:6/26/2013--Total Profit:455335.00

Region:Sub-Saharan Africa--Country:Cameroon--Item Type:Office Supplies--Order Date:11/7/2011--Total Profit:696647.50

Region:Middle East and North Africa--Country:Libya--Item Type:Clothes--Order Date:10/30/2010--Total Profit:449159.04

Region:Central America and the Caribbean--Country:Haiti--Item Type:Cosmetics--Order Date:10/13/2013--Total Profit:296448.35

Region:Sub-Saharan Africa--Country:Rwanda--Item Type:Cosmetics--Order Date:10/11/2013--Total Profit:778415.99

Region:Sub-Saharan Africa--Country:Gabon--Item Type:Personal Care--Order Date:7/8/2012--Total Profit:216919.36

Region:Central America and the Caribbean--Country:Belize--Item Type:Clothes--Order Date:7/25/2016--Total Profit:403773.12

Region:Europe--Country:Lithuania--Item Type:Office Supplies--Order Date:10/24/2010--Total Profit:1046233.75

Region:Sub-Saharan Africa--Country:Madagascar--Item Type:Clothes--Order Date:4/25/2015--Total Profit:539196.48

Region:Asia--Country:Turkmenistan--Item Type:Office Supplies--Order Date:4/23/2013--Total Profit:632512.50

Region:Middle East and North Africa--Country:Libya--Item Type:Fruits--Order Date:8/14/2015--Total Profit:1621.93

Region:Sub-Saharan Africa--Country:Democratic Republic of the Congo--Item Type:Beverages--Order Date:5/26/2011--Total Profit:89904.06

Region:Sub-Saharan Africa--Country:Djibouti--Item Type:Cereal--Order Date:5/20/2017--Total Profit:766835.04

Region:Middle East and North Africa--Country:Pakistan--Item Type:Cosmetics--Order Date:7/5/2013--Total Profit:1719922.04

Region:North America--Country:Mexico--Item Type:Household--Order Date:11/6/2014--Total Profit:1152486.42

Region:Australia and Oceania--Country:Federated States of Micronesia--Item Type:Beverages--Order Date:10/28/2014--Total Profit:146875.14

Region:Asia--Country:Laos--Item Type:Vegetables--Order Date:9/15/2011--Total Profit:235601.16

Region:Europe--Country:Monaco--Item Type:Baby Food--Order Date:5/29/2012--Total Profit:825738.04

Region:Australia and Oceania--Country:Samoa --Item Type:Cosmetics--Order Date:7/20/2013--Total Profit:1678540.98

Region:Europe--Country:Spain--Item Type:Household--Order Date:10/21/2012--Total Profit:747939.49

Region:Middle East and North Africa--Country:Lebanon--Item Type:Clothes--Order Date:9/18/2012--Total Profit:579000.96

Region:Middle East and North Africa--Country:Iran--Item Type:Cosmetics--Order Date:11/15/2016--Total Profit:1128242.43

Region:Sub-Saharan Africa--Country:Zambia--Item Type:Snacks--Order Date:1/4/2011--Total Profit:225246.90

Region:Sub-Saharan Africa--Country:Kenya--Item Type:Vegetables--Order Date:3/18/2012--Total Profit:407630.41

Region:North America--Country:Mexico--Item Type:Personal Care--Order Date:2/17/2012--Total Profit:160935.32

Region:Sub-Saharan Africa--Country:Sao Tome and Principe--Item Type:Beverages--Order Date:1/16/2011--Total Profit:138262.14

Region:Sub-Saharan Africa--Country:The Gambia--Item Type:Baby Food--Order Date:2/3/2014--Total Profit:532885.74

Region:Middle East and North Africa--Country:Kuwait--Item Type:Fruits--Order Date:4/30/2012--Total Profit:1258.02

Region:Europe--Country:Slovenia--Item Type:Beverages--Order Date:10/23/2016--Total Profit:72975.60

Region:Sub-Saharan Africa--Country:Sierra Leone--Item Type:Office Supplies--Order Date:12/6/2016--Total Profit:119685.00

Region:Australia and Oceania--Country:Australia--Item Type:Beverages--Order Date:7/7/2014--Total Profit:147031.74

Region:Middle East and North Africa--Country:Azerbaijan--Item Type:Office Supplies--Order Date:6/13/2012--Total Profit:255151.25

Region:Europe--Country:Romania--Item Type:Cosmetics--Order Date:11/26/2010--Total Profit:1375311.70

Region:Central America and the Caribbean--Country:Nicaragua--Item Type:Beverages--Order Date:2/8/2011--Total Profit:127722.96

Region:Sub-Saharan Africa--Country:Mali--Item Type:Clothes--Order Date:7/26/2011--Total Profit:65214.72

Region:Asia--Country:Malaysia--Item Type:Fruits--Order Date:11/11/2011--Total Profit:15103.47

Region:Sub-Saharan Africa--Country:Sierra Leone--Item Type:Vegetables--Order Date:6/1/2016--Total Profit:93748.05

Region:North America--Country:Mexico--Item Type:Personal Care--Order Date:7/30/2015--Total Profit:144521.02

Region:Sub-Saharan Africa--Country:Mozambique--Item Type:Household--Order Date:2/10/2012--Total Profit:889472.91

Processed 101 lines.

The reader object can handle different styles of CSV files by specifying additional parameters, some of which are shown below:

-->delimiter specifies the character used to separate each field. The default is the comma (',').

-->quotechar specifies the character used to surround fields that contain the delimiter character. The default is a double quote (' " ').

-->escapechar specifies the character used to escape the delimiter character, in case quotes aren’t used. The default is no escape character.

In [213]:
import pandas
df = pandas.read_csv('100 Sales Records.csv')
df.head(10)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2/4/2015,547995746,2/21/2015,2974,255.28,159.42,759202.72,474115.08,285087.64
6,Sub-Saharan Africa,Angola,Household,Offline,M,4/23/2011,135425221,4/27/2011,4187,668.27,502.54,2798046.49,2104134.98,693911.51
7,Sub-Saharan Africa,Burkina Faso,Vegetables,Online,H,7/17/2012,871543967,7/27/2012,8082,154.06,90.93,1245112.92,734896.26,510216.66
8,Sub-Saharan Africa,Republic of the Congo,Personal Care,Offline,M,7/14/2015,770463311,8/25/2015,6070,81.73,56.67,496101.10,343986.90,152114.20
9,Sub-Saharan Africa,Senegal,Cereal,Online,H,4/18/2014,616607081,5/30/2014,6593,205.70,117.11,1356180.10,772106.23,584073.87

In [216]:
#Pandas assumes the first line as the header
#Python by default creates a zero based index untill specified any column
#Date columns has to be specially handled in python, otherwise it will consider it as string
import pandas
df = pandas.read_csv('100 Sales Records.csv', index_col='Region')
df.head(10)

,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
Region,,,,,,,,,,,,,
Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50
Australia and Oceania,Solomon Islands,Baby Food,Online,C,2/4/2015,547995746,2/21/2015,2974,255.28,159.42,759202.72,474115.08,285087.64
Sub-Saharan Africa,Angola,Household,Offline,M,4/23/2011,135425221,4/27/2011,4187,668.27,502.54,2798046.49,2104134.98,693911.51
Sub-Saharan Africa,Burkina Faso,Vegetables,Online,H,7/17/2012,871543967,7/27/2012,8082,154.06,90.93,1245112.92,734896.26,510216.66
Sub-Saharan Africa,Republic of the Congo,Personal Care,Offline,M,7/14/2015,770463311,8/25/2015,6070,81.73,56.67,496101.10,343986.90,152114.20
Sub-Saharan Africa,Senegal,Cereal,Online,H,4/18/2014,616607081,5/30/2014,6593,205.70,117.11,1356180.10,772106.23,584073.87

In [217]:
df.columns

Index(['Country', 'Item Type', 'Sales Channel', 'Order Priority', 'Order Date',
       'Order ID', 'Ship Date', 'Units Sold', 'Unit Price', 'Unit Cost',
       'Total Revenue', 'Total Cost', 'Total Profit'],
      dtype='object')

In [222]:
#Handling date columns in pandas
import pandas
df = pandas.read_csv('100 Sales Records.csv', index_col='Region', parse_dates=['Order Date'])
df.head()

,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
Region,,,,,,,,,,,,,
Australia and Oceania,Tuvalu,Baby Food,Offline,H,2014-05-08,669165933,05-08-2014,9925,255.28,159.42,2533654.00,1582243.50,951410.50
Central America and the Caribbean,Grenada,Cereal,Online,C,2014-07-05,963881480,07-05-2014,2804,205.70,117.11,576782.80,328376.44,248406.36
Europe,Russia,Office Supplies,Offline,L,2014-05-08,341417157,05-08-2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-07-05,514321792,07-05-2014,8102,9.33,6.92,75591.66,56065.84,19525.82
Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-02-06,115456712,02-06-2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50

In [225]:
#Giving custom header names
import pandas
df = pandas.read_csv('100 Sales Records.csv', 
            index_col='Region', parse_dates=['Order_Date','Ship_Date'], 
            header=0, 
            names=['Region','Country', 'Item_Type', 'Channel', 'Order_Priority', 'Order_Date',
       'ID', 'Ship_Date', 'Units_Sold', 'Unit_Price', 'Unit_Cost',
       'Total_Revenue', 'Cost', 'Profit'])
df.head()

,Country,Item_Type,Channel,Order_Priority,Order_Date,ID,Ship_Date,Units_Sold,Unit_Price,Unit_Cost,Total_Revenue,Cost,Profit
Region,,,,,,,,,,,,,
Australia and Oceania,Tuvalu,Baby Food,Offline,H,2014-05-08,669165933,2014-05-08,9925,255.28,159.42,2533654.00,1582243.50,951410.50
Central America and the Caribbean,Grenada,Cereal,Online,C,2014-07-05,963881480,2014-07-05,2804,205.70,117.11,576782.80,328376.44,248406.36
Europe,Russia,Office Supplies,Offline,L,2014-05-08,341417157,2014-05-08,1779,651.21,524.96,1158502.59,933903.84,224598.75
Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-07-05,514321792,2014-07-05,8102,9.33,6.92,75591.66,56065.84,19525.82
Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-02-06,115456712,2013-02-06,5062,651.21,524.96,3296425.02,2657347.52,639077.50